### PR TITLE
Fix shellcheck issues

### PR DESCRIPTION
**Pull request by Bablzz**
Hello everyone!
I hope you are doing well

In this MR fixed small shellcheck.

Have a nice day

### CODE REVIEW

**Comment by gianarb** [comment]
Hello @Bablzz ! Thank you for your contribution. As you can imagine it is very hard to enforce rules like this overtime if there is not a proper check in CI.

We use [Travis](https://github.com/testcontainers/testcontainers-go/blob/master/.travis.yml) for that, and I won't merge this PR until we have a shellcheck in place for all the repo. Do you mind adding it to your pull request?

**Comment by Bablzz** [comment]
Hi @gianarb 
I don't mind:) will it do I or someone else?

**Comment by gianarb** [comment]
You please, feel free to push a commit as part of this PR

**Comment by gianarb** [comment]
Amazing! Thanks a lot

**Review by mdelapenya — COMMENTED** [review]
Great to see this!! Thanks for the contribution 👏👏👏

**Comment by Bablzz** [comment]
Thanks a lot! 
Have a great day

**Pull request merged**
