### PR TITLE
Canned kafka

### PR DESCRIPTION
**Pull request by franklinlindemberg**
I had this code around and would love to have it somehow linked to testcontainers-go.

I created this PR only to be able to refer to it in modules documentation

### CODE REVIEW

**Comment by franklinlindemberg** [comment]
Checks are failing because kafka_test is using confluent-kafka-go client, which is not supported on windows

**Comment by gianarb** [comment]
Thanks! As you probably read in the documentation https://golang.testcontainers.org/modules/ we decided to avoid a proliferation of canned /modules container as part of this library to keep it light and easy to use (without many dependencies).

A possibility for you will be to maintain this code yourself in a repo and link it in our documentation so people interesting in ready to use kafka containers will relay on your work :+1: 

I am closing this for now!

**Comment by kernle32dll** [comment]
Just some shameless self-advertisement here. I got inspired by the code here, patched it up a bit (e.g. integrating TLS), and pushed into my own repository. Credit is given.
https://github.com/kernle32dll/testcontainers-go-canned

**Comment by eddumelendez** [comment]
@kernle32dll there is a work in progress PR about adding examples. Check https://github.com/testcontainers/testcontainers-go/pull/618 and you may will to contribute. Our idea is to turn those examples to modules in the future.

**Comment by mdelapenya** [comment]
@kernle32dll we created https://github.com/testcontainers/testcontainers-go/issues/636, where you can find how to contribute new modules :)

**Pull request closed without merging**
