### PR TITLE
fix: enable formatter.require-f-funcs from testifylint

### PR DESCRIPTION
**Pull request by mmorel-35**
## What does this PR do?

Setup formatter.require-f-funcs from [testifylint](https://golangci-lint.run/usage/linters/#testifylint) linter and apply it’s recommandations .

## Why is it important?

To require f-assertions if format string is used.

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by mdelapenya** [comment]
What is your experience with this rule? I think we are doing good progress in throwing more meaningful error messages, which will be part of the test failure in the case require.Error fails. So I'm not very sure about including this one. Wdyt?

**Review by stevenh — COMMENTED** [review]
I don't understand this one, could you clarify why this change is beneficial?

**Comment by stevenh** [comment]
> I probably missed something because it's not the intention of the rule to reduce the readability of the test results, on the contrary. Let's check.
> 
> The rule reason is explained here https://github.com/Antonboom/testifylint?tab=readme-ov-file#formatter
> 
> There is also more to read https://github.com/Antonboom/testifylint?tab=readme-ov-file#historical-reference

Yer that's there to eliminate an embedded `fmt.Sprintf` as those messages are just raw strings it's not needed.

So its needed for this:
```go
assert.Errorf(t, err, fmt.Sprintf("test %s", test.testName)) // Bad
assert.Errorf(t, err, "test %s", test.testName) // Good
```

But not needed for this:
```go
assert.Error(t, err, "thing should error") // Not needed as no replaceable variables
```

**Comment by stevenh** [comment]
> Have look over here, [Antonboom/testifylint#177 (comment)](https://github.com/Antonboom/testifylint/issues/177#issuecomment-2386908481) I asked the same question to testifylint's author

Thanks for that context, really useful.

Having read the history and looked at the code for assert / require, I believe there's an case which was overlooked. If you trace the calls you'll end up in [messageFromMsgAndArgs](https://github.com/stretchr/testify/blob/v1.9.0/assert/assertions.go#L280) which has a specific case for a single argument as can be found [here](https://github.com/stretchr/testify/blob/v1.9.0/assert/assertions.go#L284).

So `f` versions are actually only required in the case where there is more than one argument.

If that rule doesn't handle that edge case I suggest we leave it disabled as it would cause churn for no real value, I would even suggest that including a reason for things like `NoError` add little to no value so would be better removed.

**Comment by stevenh** [comment]
Yes @mmorel-35 nice catch, that should be an `ErrorIs`

**Pull request closed without merging**
