### PR TITLE
Added CopyFileFromContainer to DockerContainer

### PR DESCRIPTION
**Pull request by codepitbull**
# Why ?
While working on a k3s-container I needed to extract the kubeconfig from the running container and discovered that there is no CopyFileFromContainer available.

# What ?
Added CopyFileFromContainer to DockerContainer.
Added Unit-test for the new Function.

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]
Thanks for this contribution @codepitbull, this LGTM!

**Comment by mdelapenya** [comment]
As a follow-up, would you see it doable to contribute an implementation to the compose provider? 🤔

**Comment by codepitbull** [comment]
I will checxk to add it to the ComposeProvider

**Comment by codepitbull** [comment]
About the Compose Part: There are no containers exposed.
The compose implementation as it is really just runs docker compose and can check for availability of a container.
It doesn't even allow copying files into a running container.
from what I see this qould take quite a big effort to achieve.

**Comment by mdelapenya** [comment]
> About the Compose Part: There are no containers exposed.
> The compose implementation as it is really just runs docker compose and can check for availability of a container.
> It doesn't even allow copying files into a running container.
> from what I see this qould take quite a big effort to achieve.

Sure thing. I can create an issue to add the support to the compose provider. Meanwhile, this LGTM

**Review by mdelapenya — APPROVED** [review]

**Comment by gianarb** [comment]
Hello! Thank you for your contribution! I had a chat with @mdelapenya via Slack and I would like to know what you think about this:

```
	CopyFileToContainer(ctx context.Context, hostFilePath string, containerFilePath string, fileMode int64) error
	CopyFileFromContainer(ctx context.Context, filePath string) ([]byte, error)
```

I see how your function will may come from what we have done with `CopyFileToContainer` but now that I see it if I think we made a mistake there (I think we should deprecate that in favor of something else).

I think the right signature should be:

```
	CopyFileFromContainer(ctx context.Context, filePath string) (io.ReadCloser, error)
``` 

This works a bit better over the network and it five more control to the end user who can decide what to do with an `io.Reader`.

I understand the extra code you wrote sounds like a useful utility function but at the end it can be replaced with a few line as explained here https://pkg.go.dev/io/ioutil#ReadAll and I don't think it should be something to include as part of the testcontainer library.

What do you think?

**Comment by codepitbull** [comment]
Hey @gianarb,
thanks for your feedback :)
I have updated my Pr to use the signature you suggested.
With your suggestions in mind I also thought it would be better to eliminate all eager reading.
I wrapped the whole tar reader to enable closing of the underlying ReaderCloser and to return a valid object.
You think this would work better?

Cheers,
Jochen

**Comment by codepitbull** [comment]
Hey @mdelapenya or @gianarb ,
are you interested in this? Anything else you would like to see changed/added in here?
Cheers,
Jochen

**Review by mdelapenya — APPROVED** [review]
This LGTM! Thanks again for this contribution and for your patience. I usually wait for @gianarb performing the merges, so let's wait for that review.

**Comment by mdelapenya** [comment]
BTW, the GH action complains about source formatting in the `docker.go` file.

Could you run `./scripts/checks.sh` and verify the issue? 🙏

**Comment by codepitbull** [comment]
@mdelapenya fixed it, forgot to run "go fmt" ...

**Comment by codepitbull** [comment]
And just so you know what this is for:
Thanks to a few hints from @bsideup I was able to implement k3s-based integrationtests for k8s.
The only missing piece was this function.

Here is the example of what I am using it for:
https://github.com/codepitbull/k8sit/blob/main/gok3s/k8sit/testcontainer_test.go

**Comment by gianarb** [comment]
Thank you for this!!

**Comment by codepitbull** [comment]
Thanks to you and the other maintainers!
We are really happy with it for our integration tests :)

**Pull request merged**
