### PR TITLE
Reaper container should not be labeled with "org.testcontainers.golang.sessionId"

### LINKED ISSUE #698: [Bug]: Ryuk kills itself before removing networks, volumes and images
### Testcontainers version

v0.16.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

1.19

### Docker version

```shell
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 12
  Running: 2
  Paused: 0
  Stopped: 10
 Images: 37
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-26-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.25GiB
 Name: thor
 ID: S4XQ:6LAR:AMRS:JRG5:FPSO:NXHA:AD7P:TEZF:Y6FQ:RQ6R:NB46:CUQ7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Since reaper container gets the `org.testcontainers.golang.sessionId` label:

https://github.com/testcontainers/testcontainers-go/blob/71461a93b65a712ec1bf7e962f8932986ffa9b7f/reaper.go#L74-L77

```
docker container inspect -f '{{.Config.Labels}}' f4afaff6443e 
map[org.testcontainers.golang:true org.testcontainers.golang.reaper:true org.testcontainers.golang.sessionId:9f7e7a47-db4b-4e8b-b1b5-7510e230a1db]
```
When the cleanup code is not run, because of panic for example, the reaper will trigger purging but doing so it will remove itself not getting to the networks, volumes and images. See ryuk code:

https://github.com/testcontainers/moby-ryuk/blob/8f512d37699cb6e5a3b28f2433c2b3b894a78e5d/main.go#L191-L240

The behavior may be seen looking at ryuk container logs as well:

```
2022/12/16 17:23:47 Pinging Docker...
2022/12/16 17:23:47 Docker daemon is available!
2022/12/16 17:23:47 Starting on port 8080...
2022/12/16 17:23:47 Started!
2022/12/16 17:23:47 New client connected: 172.17.0.1:49952
2022/12/16 17:23:47 EOF
2022/12/16 17:23:47 Client disconnected: 172.17.0.1:49952
2022/12/16 17:23:47 New client connected: 172.17.0.1:49966
2022/12/16 17:23:51 Adding {"label":{"org.testcontainers.golang.sessionId=edabcbdf-613d-4463-a04f-8cffbb351112":true,"org.testcontainers.golang=true":true}}
2022/12/16 17:23:51 New client connected: 172.17.0.1:49968
2022/12/16 17:23:51 EOF
2022/12/16 17:23:51 Client disconnected: 172.17.0.1:49968
2022/12/16 17:24:13 EOF
2022/12/16 17:24:13 Client disconnected: 172.17.0.1:49966
2022/12/16 17:24:23 Timed out waiting for re-connection
2022/12/16 17:24:23 Deleting {"label":{"org.testcontainers.golang.sessionId=edabcbdf-613d-4463-a04f-8cffbb351112":true,"org.testcontainers.golang=true":true}}
```

The final line 

https://github.com/testcontainers/moby-ryuk/blob/8f512d37699cb6e5a3b28f2433c2b3b894a78e5d/main.go#L61

is never displayed.

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rzajac**
….sessionId. Fixes #698.

Sorry something strange happened to previous PR

### CODE REVIEW

**Review by HofmeisterAn — APPROVED** [review]
Without having a lot of experience in the Go implementation I think the PR looks good. `AutoRemove` equals `true` and the session ID label gets skipped.

**Comment by rzajac** [comment]
Is there anything I can do to have it merged?

**Comment by HofmeisterAn** [comment]
Manu is expected to be back next week. I am certain we will address it until the end of next week.

**Comment by mdelapenya** [comment]
I think it's fine to remove the sessionId label from the Ryuk container request. Relates to https://github.com/testcontainers/moby-ryuk/pull/53

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks for your time adding this check, much appreciated 🙏

**Pull request merged**
