### PR TITLE
test: continue tests where possible

### PR DESCRIPTION
**Pull request by JoelLau**
## What does this PR do?

- replaced `assert` with `require` where possible

## Why is it important?

- increase the amount of information in each test by continuing execution
    - NOTE: i've only made changes where i think assertions can be made in parallel (in theory), where failing an assertion will not lead to an error state in subsequent tests

## Related issues

- Relates #2808

### CODE REVIEW

**Review by stevenh — CHANGES_REQUESTED** [review]
I'm actually not a fan of this approach as it just tends to result in a lot of noise which creates little to no value, better to just fail on the first error.

**Comment by mdelapenya** [comment]
Exactly, the intent is just the opposite, and use `require` over `assert` if/when possible.

**Comment by stevenh** [comment]
Given this is only replacing `require` with `assert` which is moving in the wrong way, I'm going to close this as it will be easier to create a new one moving in the right direction.

**Comment by JoelLau** [comment]
my bad, idk how i got it the wrong way around. thanks for looking at this and sorry for the noise

**Comment by stevenh** [comment]
Thank you for the effort @JoelLau, its great to have community engagement, that's that open source is all about 🥇

**Pull request closed without merging**
