### PR TITLE
ci(lint): enable misspell and gci linters

### PR DESCRIPTION
**Pull request by mmorel-35**
## What does this PR do?

Enables [misspell](https://golangci-lint.run/usage/linters/#misspell) and [gci](https://golangci-lint.run/usage/linters/#gci) linters

## Why is it important?

Fixes and prevent misspellings and organize in a fixed order the dependencies imports.

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]
Thanks for this tiny and super valuable contribution!!

I've been thinking about it since ever, so super glad you had the time to add them to our golangci config 👏 

LGTM 👍 

image

**Comment by mmorel-35** [comment]
Hi @mdelapenya,

Do you have a list you would like to add ?
I can give it a try.

**Comment by mdelapenya** [comment]
> Hi @mdelapenya,
> 
> Do you have a list of linters you would like to add ? I can give it a try.

Not at this moment but the spell checker you added here.

If you want to add one or more, let's open a discussion with it. wdyt?

BTW, I'm merging this little one now 🚀  thanks!

**Comment by mmorel-35** [comment]
> If you want to add one or more, let's open a discussion with it. wdyt?


OK !

**Pull request merged**
