### PR TITLE
Added Kafka (KRaft Mode) module

### PR DESCRIPTION
**Pull request by noctarius**
## What does this PR do?

This PR adds a new module for Kafka, running in KRaft (Zookeeper-less) mode

## Why is it important?

New modules are always important :-)

## Related issues

- Relates #1033 

## How to test this PR

Simple test for the module is included

### CODE REVIEW

**Comment by mdelapenya** [comment]
Hi @noctarius this is awesome! I have one question regarding how you created the scaffolding, as I'm not sure if you used the module generator tool, as described [here](https://golang.testcontainers.org/modules/#interested-in-adding-a-new-module)? 

It will generate the scaffolding and will automatically add it to the docs site (golang.testcontainers.org).

**Comment by noctarius** [comment]
I just copy and pasted what I found for other modules, so no, I didn't use the tool 🤷‍♂️
Let me run it now and see what comes out of it

**Comment by mdelapenya** [comment]
Hey @noctarius sorry for the radio silence, but we have been working on a more consistent module design, so I'd ask you to visit the docs on how to adhere to this design here: https://golang.testcontainers.org/modules/

In two sentences, the entrypoint must be `RunContainer(ctx, opts ...testcontainers.ContainerCustomizer` and we explain there how to create own in-module customizers. The Couchbase module is a good place to look at how to transfer state from the container request to the running container where there is data that does not belong to the container request type.

I'd be very happy to review your PR following this new design 🙏

**Comment by weeco** [comment]
@noctarius Just recently we released an official Redpanda module, maybe that helps you for integration tests. It starts faster than the Kafka module, it's Kafka API compatible and also comes with schema registry support.

**Comment by mdelapenya** [comment]
@noctarius this you take a look at https://github.com/testcontainers/testcontainers-go/pull/1034#issuecomment-1538334441?

In any case, please let me know if you want to keep this Kafka module, I could dedicate time with you to update the PR to use the new design for modules

**Comment by srenatus** [comment]
Just a comment from the sidelines, I think it's worthwhile to keep this. If you're testing an application that should be compatible with Apache Kafka and Redpanda, I think it does make sense to test with them both.

**Comment by mdelapenya** [comment]
> I think it does make sense to test with them both.

@srenatus cool then. Is anybody willing to contribute it? I'd start a new PR, or rewrite this one, using the new APIs for modules, just copying the functionality in this PR.

**Comment by noctarius** [comment]
Hey folks! Sorry for the long abstinence. Happy to make a new version of this but not sure when I get to that. If anyone wants to chime in, feel free :)

**Comment by mdelapenya** [comment]
I have a working PR for this. Will submit and close this one.

Thanks for the initial work here @noctarius!! I will add you to #636 as contributor of the kafka module

**Pull request closed without merging**
