### PR TITLE
allow alternative reaper docker registry

### PR DESCRIPTION
**Pull request by makasprzak**
In our project we are obliged to pull docker images through a corporate docker registry mirror. The problem is that the image for the resource reaper (ryuk) is right now hardcoded. Therefore I'm proposing this little patch to work this around. Please see if you can make any use of it. Thanks

### CODE REVIEW

**Comment by ClaytonNorthey92** [comment]
instead of only allowing the specifying of the registry, should we just allow the user to specify the entire reaper image?  it looks like that is [what the java project does](https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper)

**Comment by makasprzak** [comment]
Fair point @ClaytonNorthey92 , I applied the change

**Comment by ClaytonNorthey92** [comment]
thank you @makasprzak !

**Comment by gianarb** [comment]
Thanks for coding this and for the reviews!! YOU are amazing!

**Pull request merged**
