### PR TITLE
modulegen: create internal/module and internal/modfile

### PR DESCRIPTION
**Pull request by mmorel-35**
## What does this PR do?

This PR move the logic of go.mod construction from main package to internal/modfile package.
It also replaces the use of a template to the use of golang.org/x/mod library. This allows to read the go version and the main package informations from the main go.mod and use it to construct the new module.
As there is no more template for go.mod, the script for updating go version is updated too.

It also moves the construction of example.go and example_test.go to internal/module.

As the testcontainer-go version is directly retrieved from mkdocs.yml this property is not provided as an Example property.

## Why is it important?
This is separating code in there domain to improve the readability and maintanability.

## Related issues
- Relates #1536

## Follow-ups
- Relates #1543

### CODE REVIEW

**Review by mdelapenya — DISMISSED** [review]
Cool, thanks! This LGTM and it's ready to be merged 👏  I myself understand the code but anybody else in the community could not understand the rationale behind the usage of `gomod` Vs keeping the template. BTW this is cool!

I'd appreciate if you use the PR template to include a description of what this PR does (technical implementation) and why is needed (product needs), because I see PR descriptions as a way of documentation for these two personas: a community member, and the future ourselves in the need to check why we did something in such a way in the past.

So I'd ask you for filling in the PR description before merging it 🙏

**Comment by mmorel-35** [comment]
Ok @mdelapenya ,
Does this description is enough or do you need me to precise more on certain parts ?

**Comment by mdelapenya** [comment]
> Ok @mdelapenya , Does this description is enough or do you need me to precise more on certain parts ?

Now it's perfect. Thanks for your hard work improving the module generator 🚀

**Comment by mmorel-35** [comment]
There was a typo in some names "mode" instead of "mod" was used.

**Pull request merged**
