### PR TITLE
feature: add support tty

### PR DESCRIPTION
**Pull request by crashiura**
Add tty for container

This fix issue [365](https://github.com/testcontainers/testcontainers-go/issues/365)

### CODE REVIEW

**Comment by funvit** [comment]
I am think this can break `docker.go (c *DockerContainer) StartLogProducer`...

**Comment by mdelapenya** [comment]
> I am think this can break `docker.go (c *DockerContainer) StartLogProducer`...

@funvit could you please elaborate a bit more about it?

**Comment by mdelapenya** [comment]
@crashiura @funvit do you think that, after #454, this can be closed?

**Comment by crashiura** [comment]
@mdelapenya Hi, I think yes

**Pull request closed without merging**
