### PR TITLE
chore(deps): bump github.com/docker/docker from v26.1.4 to v27.0.2

### PR DESCRIPTION
**Pull request by thaJeztah**
diffs:

- https://github.com/docker/docker/compare/v26.1.4..v27.0.2
- https://github.com/docker/cli/compare/v26.1.4..v27.0.2
- https://github.com/distribution/reference/compare/v0.5.0...v0.6.0
- https://github.com/docker/compose/compare/v2.27.0...v2.28.1

## Related issues

-

### CODE REVIEW

**Comment by mdelapenya** [comment]
Hey @thaJeztah I'm seeing an error in the compose module, which I updated its dependencies locally, bumping `docker/cli` to `v27`too. The error is:

``` 
::error file=compose.go,line=15,col=2::could not import github.com/docker/compose/v2/pkg/api (-: # github.com/docker/compose/v2/pkg/api
../../../../../../pkg/mod/github.com/docker/compose/v2@v2.27.1/pkg/api/dryrunclient.go:56:26: cannot use &DryRunClient{} (value of type *DryRunClient) as "github.com/docker/docker/client".APIClient value in variable declaration: *DryRunClient does not implement "github.com/docker/docker/client".APIClient (wrong type for method ImageImport)
                have ImageImport("context".Context, "github.com/docker/docker/api/types".ImageImportSource, string, image.ImportOptions) ("io".ReadCloser, error)
                want ImageImport("context".Context, image.ImportSource, string, image.ImportOptions) ("io".ReadCloser, error)
../../../../../../pkg/mod/github.com/docker/compose/v2@v2.27.1/pkg/api/dryrunclient.go:109:15: cannot use struct{NetworkMode string `json:",omitempty"`}{} (value of type struct{NetworkMode string "json:\",omitempty\""}) as struct{NetworkMode string "json:\",omitempty\""; Annotations map[string]string "json:\",omitempty\""} value in struct literal
../../../../../../pkg/mod/github.com/docker/compose/v2@v2.27.1/pkg/api/dryrunclient.go:431:38: cannot use source (variable of type "github.com/docker/docker/api/types".ImageImportSource) as image.ImportSource value in argument to d.apiClient.ImageImport) (typecheck)
::error file=compose_api.go,line=93,col=4::o.RemoveOrphans undefined (type *stackDownOptions has no field or method RemoveOrphans) (typecheck)
::error file=compose_api.go,line=106,col=4::o.Volumes undefined (type *stackDownOptions has no field or method Volumes) (typecheck)
::error file=compose_api.go,line=115,col=5::o.Images undefined (type *stackDownOptions has no field or method Images) (typecheck)
::error file=compose_api.go,line=117,col=5::o.Images undefined (type *stackDownOptions has no field or method Images) (typecheck)
::error file=compose_api.go,line=11,col=2::"strings" imported and not used (typecheck)
```

Something to mention to the compose team?

**Comment by thaJeztah** [comment]
Hmm.. right so looks like Compose must be adjusted for v27, which I think was being worked on, but I wonder if that could cause issues with buildx, which depends on compose-go and cli 🤔 

Oh, perhaps compose-go is not problematic here, so maybe we're good; at least, once compose was updated for v27? 

cc @akerouanton @glours

**Comment by thaJeztah** [comment]
Updated the compose module with https://github.com/docker/compose/pull/11926, which is a WIP branch for updating compose to v27.0

**Comment by robertjndw** [comment]
Hey guys, any idea when this PR might be merged? 😅

**Review by mdelapenya — DISMISSED** [review]
Thank you @thaJeztah for updating all references. Huge work.

LGTM!

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!

**Comment by Mtze** [comment]
Thanks for fixing :)

**Pull request merged**
