### PR TITLE
add containerised docker compose and tests

### PR DESCRIPTION
**Pull request by mazitovt**
Feature for Issue #425

Added `ContainerisedDockerCompose` struct with embedded `LocalDockerCompose` and override all `DockerCompose` methods. Added two functions `executeInContainer` and `executeComposeInContainer`, that work with docker/compose container.

### CODE REVIEW

**Comment by mazitovt** [comment]
@mdelapenya, hi. You've mentioned my PR, but never gave a feedback. Can you please review it?

**Comment by mdelapenya** [comment]
> @mdelapenya, hi. You've mentioned my PR, but never gave a feedback. Can you please review it?

Hi @mazitovt this compose has different "rivals" :) 
- https://github.com/testcontainers/testcontainers-go/pull/462
- and more importantly this discussion about the future of compose: https://github.com/testcontainers/testcontainers-go/issues/425#issuecomment-1165237887

I pinged you in the issue just in case you want to participate in it to design what compose APIs we want to have

Again, sorry if I should have been more responsive in this PR 🙏

**Comment by mdelapenya** [comment]
Hi @mazitovt we have merged #476, which adds native support for docker compose, deprecating the local docker compose implementation. I'm not sure if we'd need a dockerised one now that we can run it natively, but wanted to check with you first before closing this issue.

**Comment by mazitovt** [comment]
@mdelapenya ok. I close my PR.

**Pull request closed without merging**
