### PR TITLE
#145 Update default reaper images to 0.2.3

### PR DESCRIPTION
**Pull request by Bablzz**
Hello everybody!

In this version reaper fixed 
https://quay.io/repository/testcontainers/ryuk/manifest/sha256:bb5a635cac4bd96c93cc476969ce11dc56436238ec7cd028d0524462f4739dd9?tab=vulnerabilities

### CODE REVIEW

**Comment by Bablzz** [comment]
#148

**Comment by Bablzz** [comment]
#145

**Comment by Bablzz** [comment]
My pleasure to contribute in this project!

**Comment by gianarb** [comment]
Thanks!

**Pull request merged**
