### PR TITLE
chore(gha): use official docker/setup-docker-action

### PR DESCRIPTION
**Pull request by vvoland**
## What does this PR do?
Use our official github action to setup rootless docker

## Related issues

-

### CODE REVIEW

**Review by mdelapenya — DISMISSED** [review]
Fantastic! Looks great using an official image for this, thank you so much 👏

**Comment by mdelapenya** [comment]
@vvoland please let me know when this is ready to be merged 🙏

**Comment by vvoland** [comment]
Dropped the last commit that ran the nightly tests on this PR. Should be ready to go now 👍🏻

**Review by mdelapenya — APPROVED** [review]
Awesome!

image

**Pull request merged**
