### PR TITLE
Log producer start stop sync

### PR DESCRIPTION
**Pull request by gflarity**
## What does this PR do?

As part of trying to fix the issues discuss in #1700, I tried this first. Turns out  the lack of sychronization in StartLogProducer and StopLogProducer was actually red herring, however it seems like is still a useful addition so I thought I'd send out the PR for review. 

## Why is it important?

Makes (Start/Stop)LogProducer  more deterministic and perhaps will prevent future race condition bugs.

### CODE REVIEW

**Review by mdelapenya — DISMISSED** [review]
Let's wait until #1700 is merged to rebase this one, as they share the changeset.

Other than that, LGTM, thanks!

**Comment by mdelapenya** [comment]
Oh well, this PR needs to be formatted. Could you please run `make lint` from the top of the project? 🙏

**Comment by mdelapenya** [comment]
@gflarity since #1700 was already merge, I think we can work on simplifying this PR. Could you take a look please? :pray:

**Comment by gflarity** [comment]
> @gflarity since #1700 was already merge, I think we can work on simplifying this PR. Could you take a look please? 🙏

Yup, I've just rebased on main. Will update PR after tests pass :)

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
