### PR TITLE
Simplify dependabot updates sorting

### PR DESCRIPTION
**Pull request by mmorel-35**
Use the sorter capabilities to handle the sorting.
It uses the package-ecosystem and the directory. 
I know that the result is a bit different from the actual.

### CODE REVIEW

**Comment by mdelapenya** [comment]
IIUC it will use gh-actions > gomod > pip, so the code is sorting by package-ecosystem too. I like it! TBH I considered enforcing the extras (gha, pip) first and then the go code, but thinking about it twice, why? 🙈 

I do like this approach mode, as it more deterministic and based on a personal bias. Thanks for this!

**Review by mdelapenya — APPROVED** [review]
LGTM! Thanks

**Comment by mdelapenya** [comment]
My only concern (unrelated) is that any time the dependabot file is modified, it triggers an update 🤦 So be ready for YADW: Yet Another Dependabot Wave

**Comment by mmorel-35** [comment]
You shouldn't be concerned about this. Maybe the amount of allowed PR per module is too low or the check frequency too long.
The config need help you address every update as soon as possible. If there are new updates every time there is a problem with the configuration.

**Comment by mdelapenya** [comment]
I was expecting @dependabot to be smart enough to honour the monthly schedule, instead of triggering an update every time the file is modified, which happened today after this merge

**Pull request merged**
