### PR TITLE
Add neo4j license agreement customization options

### PR DESCRIPTION
**Pull request by danielorbach**
## What does this PR do?

This PR adds the ability to use the Neo4j Enterprise Edition docker image by setting the correct environment variable.

## Why is it important?

Many production-ready users of Neo4j use the Enterprise edition. Some features can only be tested on the Enterprise edition.

## Related issues

I haven't opened a concomitant Issue, @mdelapenya let me know if I should open one.

## How to test this PR

Simply run a container with image tag `enterprise` (i.e. `neo4j:enterprise`) with the new option and see that the container does not crash immediately with the following error:

<details><summary>Details</summary>
<p>

```text
In order to use Neo4j Enterprise Edition you must accept the license agreement.
  
  The license agreement is available at https://neo4j.com/terms/licensing/
  If you have a support contract the following terms apply https://neo4j.com/terms/support-terms/
  
  If you do not have a commercial license and want to evaluate the Software
  please read the terms of the evaluation agreement before you accept.
  https://neo4j.com/terms/enterprise_us/
  
  (c) Neo4j Sweden AB. All Rights Reserved.
  Use of this Software without a proper commercial license, or evaluation license
  with Neo4j, Inc. or its affiliates is prohibited.
  Neo4j has the right to terminate your usage if you are not compliant.
  
  More information is also available at: https://neo4j.com/licensing/
  If you have further inquiries about licensing, please contact us via https://neo4j.com/contact-us/
  
  To accept the commercial license agreement set the environment variable
  NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  
  To accept the terms of the evaluation agreement set the environment variable
  NEO4J_ACCEPT_LICENSE_AGREEMENT=eval
  
  To do this you can use the following docker argument:
  
          --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=<yes|eval>
```

</p>
</details>

### CODE REVIEW

**Review by mdelapenya — COMMENTED** [review]
Do the options require a specific Docker image for Neo4j? I'd like to have a test or a testable example demonstrating the usage of this options

**Comment by mdelapenya** [comment]
Oh I saw this late:
> Simply run a container with image tag enterprise 

What will happen when the options are passed with a non-enterprise image? Will that be a NOOP?

**Comment by danielorbach** [comment]
> What will happen when the options are passed with a non-enterprise image? Will that be a NOOP?

Yes indeed a no-op. 

/to @mdelapenya

**Comment by mdelapenya** [comment]
> > What will happen when the options are passed with a non-enterprise image? Will that be a NOOP?
> 
> Yes indeed a no-op.
> 
> /to @mdelapenya

So then it's fine to pass the options in a non-enterprise image, right? Then, having a test/example would make it to be merged

**Comment by danielorbach** [comment]
> > > What will happen when the options are passed with a non-enterprise image? Will that be a NOOP?
> > 
> > 
> > Yes indeed a no-op.
> > /to @mdelapenya
> 
> So then it's fine to pass the options in a non-enterprise image, right? Then, having a test/example would make it to be merged

I've pushed some tests proving that @mdelapenya

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks for adding the test and for contributing to the module. Much appreciated!

**Pull request merged**
