### PR TITLE
Docker compose: Add the output of the command to the returning struct

### PR DESCRIPTION
**Pull request by oriser**
There was no interface for getting the output of the compose command after calling `Invoke`.
Because you are allowing running any command (using `WithCommand`), it is essential that the user will be able to get the output of the command.

I saw that you're already implemented `capturingPassThroughWriter` that copies the output to a buffer as well as stdout\stderr, so I used it and just added the output to the returning struct.

### CODE REVIEW

**Comment by oriser** [comment]
Looks like the CI is broken
image

**Comment by oriser** [comment]
@mdelapenya Can we merge it?

**Comment by mdelapenya** [comment]
We are starting to see the following error for PRs using Go 1.x (1.18). For some reason `gotestsum` is not found in the test runner.

Screenshot 2022-04-04 at 10 52 11

**Comment by mdelapenya** [comment]
I think we have the dependencies resolved here: https://github.com/testcontainers/testcontainers-go/pull/421

**Comment by oriser** [comment]
> I think we have the dependencies resolved here: #421
> 
> Could you please merge your branch on top of current master? 🙏

done

**Comment by oriser** [comment]
@mdelapenya Is there anything else?

**Review by gianarb — APPROVED** [review]

**Review by mdelapenya — APPROVED** [review]
LGTM! thanks for taking the time to contribute!

**Pull request merged**
