### PR TITLE
[Enhancement]: add ability to set repo:tag for ContainerRequest FromDockerfile

### PR DESCRIPTION
**Pull request by igribkov**
## What does this PR do?

This PR adds an ability to set ```repo:tag``` for ContainerRequest FromDockerfile

## Related issues
- Closes https://github.com/testcontainers/testcontainers-go/issues/1507

### CODE REVIEW

**Review by mdelapenya — CHANGES_REQUESTED** [review]
LGTM although I'd like to have a test for the new behaviour. Would you mind adding it? 🙏 

Once there, I think this is ready to be merged 🚀 

Thanks!

**Comment by mdelapenya** [comment]
Hi @igribkov 👋 I went ahead and added a test here: https://github.com/testcontainers/testcontainers-go/pull/1508/commits/6b5d098f7c993a728ac3d6dcabae133df412d518

Please let me know if that's fine.

Cheers!

**Review by mdelapenya — APPROVED** [review]

**Comment by igribkov** [comment]
@mdelapenya, sorry for so late response, i was on vacation and totally offline, i'm very sorry that you had to do my work :(
\tests look fine

**Comment by mdelapenya** [comment]
@igribkov no worries at all! I totally understand, taking time off goes first!

I was so ecstatic about the feature that I wanted to include it the soonest. Don't feel sorry 🙏 You did a great work requesting the new feature and implementing it 😉 

Thanks again for your time contributing to testcontainers-go 🚀

**Pull request merged**
