### PR TITLE
Update docker version to v19.03.8

### PR DESCRIPTION
**Pull request by ImVexed**
Resolves https://github.com/testcontainers/testcontainers-go/issues/152 & https://github.com/testcontainers/testcontainers-go/issues/143

### CODE REVIEW

**Comment by gianarb** [comment]
I think I will never get how gomod works.

https://github.com/testcontainers/testcontainers-go/blob/master/go.mod#L37

This line is supposed to replace the use of docker/docker with docker/engine. So should we remove that as well?

**Comment by ImVexed** [comment]
I also do not understand how gomod works.

Also I thought 19.03.8 worked for me but upon a `go clean --modcache` and deletion of my `go.sum` it broke again until I used the most recent commit off of master. I have no idea why it works.

**Comment by gianarb** [comment]
I think go mod does not manage transient dependencies, so the `replace` will fix the problem you have but it is applied to your application, not to testcontainers. Testcontainer itself as you see from our CI works with the version we pin.

You `replace` docker in your project, and that makes everything to work for your app as you wrote, but from  testcontainer standpoint, unfortunately, we can't fix that

**Comment by tomqwpl** [comment]
Since I'm also having this problem, can someone explain the fix? Can I resolve this locally?
I cloned ImVexed's repository and have used it locally with success (I had to clone so that I could change the package name in go.mod, otherwise go then complained about it not matching the repository name)

**Comment by gianarb** [comment]
This explains what I am trying to say I think: https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

> replace directives provide additional control in the top-level go.mod for what is actually used to satisfy a dependency found in the Go source or go.mod files, while replace directives in modules other than the main module are ignored when building the main module.

`replace` directive placed in a library like this one (used by your application) is not used from your main application.

So you can apply the `replace` you need directly in your app. Because adding a `replace` here won't fix the problem you have in your app.

At least this is what I got until now :disappointed:

**Comment by tomqwpl** [comment]
Ah, OK. That's worked for me:

    replace github.com/docker/docker => github.com/docker/docker v17.12.0-ce-rc1.0.20200416190941-2200d938a2d5+incompatible

I don't get why I have to do this though. Are you saying it's not a bug?

**Comment by gianarb** [comment]
No this is how Go designed the `gomod` dependency manager. Have a look at the link I posted it contains a lot of hidden gems about `gomod` itself.

**Comment by gianarb** [comment]
As I think it is clear at this point there is not much we can do about this PR.
I am closing for now. Feel free to open it again or ping me here

**Pull request closed without merging**
